version: "3.8"
services:
  web:
    build: .
    container_name: nextjs-app
    ports:
      - "80:80"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - PORT=80
    restart: unless-stopped
