name: Deploy to AWS ECR

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region ap-southeast-1 | docker login --username AWS --password-stdin 409151997352.dkr.ecr.ap-southeast-1.amazonaws.com

      - name: Build and tag Docker image
        run: |
          docker build -t product-microservice .
          docker tag product-microservice:latest 409151997352.dkr.ecr.ap-southeast-1.amazonaws.com/ass-backend:rentify-latest

      - name: Push Docker image to ECR
        run: |
          docker push 409151997352.dkr.ecr.ap-southeast-1.amazonaws.com/ass-backend:rentify-latest
